apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 37b357c48e7cbe9ba8b78fac729cb964fdb2c5fa
  application.deploy.reform/deploymentNo: kenny-app-1-dev-approval_DP11
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: kenny-app-1
  application.deploy.reform/repository: https://github.com/kreslv/reform-deployment.git
  application.deploy.reform/repositoryPath: kenny-app-1
  application.deploy.reform/revision: 2023.04.11
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
