apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: e2d46aca15c4f40bb0d52e61432dd59207244ca1
    application.deploy.reform/deploymentNo: kenny-app-2-dev-approval_DP1
    application.deploy.reform/environment: dev-approval
    application.deploy.reform/name: kenny-app-2
    application.deploy.reform/repository: https://github.com/kreslv/reform-deployment.git
    application.deploy.reform/repositoryPath: kenny-app-2
    application.deploy.reform/revision: 2023.04.1
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 6b5c82cf8fbd6720e41370072c0193f4158e3f6c
  creationTimestamp: null
  name: kenny-app-2
  namespace: uat
spec:
  components:
  - name: kenny-app-2-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.4"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  - name: kenny-app-2-api-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
