apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 7cb16e6bc809ac3e9445f2c0dac3bc662739830e
  application.deploy.reform/deploymentNo: qc-deploy-003-dev-approval_DP1
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: qc-deploy-003
  application.deploy.reform/repository: https://github.com/kreslv/reform-deployment.git
  application.deploy.reform/repositoryPath: qc-deploy-003
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
