apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: kenny-app-1
  namespace: vela-system
spec:
  components:
  - name: kenny-app-1-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.1"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 8Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
status: {}
