apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: _
  creationTimestamp: null
  name: kenny-app-1
  namespace: uat
spec:
  components:
  - name: kenny-app-1-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.1"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 16Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
