apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 3ae826b9c844a43f2fb5f0cceb2190a93e8744c6
  application.deploy.reform/deploymentNo: app-demo-dev-approval_DP4
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: app-demo
  application.deploy.reform/repository: https://github.com/kreslv/reform-deployment.git
  application.deploy.reform/repositoryPath: app-demo
  application.deploy.reform/revision: 2023.04.4
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
