apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 41473089ac0dcd48e9fd8d5fc9644ff7d21bffd8
  application.deploy.reform/deploymentNo: app-demo-dev-approval_DP2
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: app-demo
  application.deploy.reform/repository: https://github.com/kreslv/reform-deployment.git
  application.deploy.reform/repositoryPath: app-demo
  application.deploy.reform/revision: 2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
