apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: e46d489da75292caec3094555db90fa54793fe30
  application.deploy.reform/deploymentNo: demo-2-dev-approval_DP3
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: demo-2
  application.deploy.reform/repository: https://github.com/kreslv/reform-deployment.git
  application.deploy.reform/repositoryPath: demo-2
  application.deploy.reform/revision: 2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
